version: '3'

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    ports:
    - 8000:80
    volumes:
    - ./logs:/var/www/html/storage/logs
    depends_on:
    - mariadb
    - redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  # caddy:
  #   image: caddy:latest
  #   ports:
  #   - 8000:80
  #   - 8443:443
  #   volumes:
  #   - ./Caddyfile:/etc/caddy/Caddyfile
  #   env_file:
  #   - .env.docker
  #   networks:
  #   - snipeit-backend

  mariadb:
    image: mariadb:latest
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  redis:
    image: redis:latest
    networks:
    - snipeit-backend

  mailhog:
    image: mailhog/mailhog:latest
    ports:
    # - 1025:1025
    - 8025:8025
    networks:
    - snipeit-backend



volumes:
  db: {}

networks:
  snipeit-backend: {}