version: '3'

services:

  snipeit:
    build:
      context: .
      dockerfile: res/Dockerfile.fpm-alpine
    container_name: snipe-it
    restart: always
    volumes:
      - snipeit-logs:/var/www/html/storage/logs
      - snipeit-data:/var/www/html
    depends_on:
      - database
      - redis
      - nginx
    env_file:
      - res/setting-env.dev
    networks:
      - internal

  nginx:
    image: nginx:mainline
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - snipeit-data:/var/www/html
      - nginx-log:/var/log/nginx
    restart: always
    ports:
      - "8080:8080"
    networks:
      - internal

  database:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - res/setting-env.dev
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass D7JGk74*7bbb
    networks:
      - internal

volumes:
  mysql:
  nginx-conf:
  nginx-log:
  snipeit-logs:
  snipeit-data:

networks:
  internal:
    driver: bridge